services:
  - type: web
    name: gr-transport
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromGroup: gr-transport-env
      - key: JWT_SECRET
        fromGroup: gr-transport-env
      - key: ADMIN_PIN
        fromGroup: gr-transport-env

envVarGroups:
  - name: gr-transport-env
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_PIN
        sync: false
